# Generated by Django 2.2.4 on 2019-09-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('view_cnt', models.IntegerField(blank=True, null=True)),
                ('thumbup_cnt', models.IntegerField(blank=True, null=True)),
                ('thumbdown_cnt', models.IntegerField(blank=True, null=True)),
                ('icxthumbup_cnt', models.IntegerField(blank=True, null=True)),
                ('icxthumbdown_cnt', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('description', models.CharField(default='디폴트', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(null=True)),
                ('thumbup_cnt', models.IntegerField(blank=True, null=True)),
                ('thumbdown_cnt', models.IntegerField(blank=True, null=True)),
                ('icxthumbup_cnt', models.IntegerField(blank=True, null=True)),
                ('icxthumbdown_cnt', models.IntegerField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.ArticleModel')),
            ],
        ),
        migrations.CreateModel(
            name='ThumbModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up', models.IntegerField(blank=True)),
                ('down', models.IntegerField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.ArticleModel')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.CommentModel')),
            ],
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.BoardModel'),
        ),
    ]
