# Generated by Django 2.2.4 on 2019-09-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20191001_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='contents',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='icxthumbdown_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='icxthumbup_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='thumbdown_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='thumbup_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='view_cnt',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
