# Generated by Django 2.2.4 on 2019-09-30 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20191001_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleboard',
            name='category',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='icxthumbdown_cnt',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='icxthumbup_cnt',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='thumbdown_cnt',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='thumbup_cnt',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='icxthumbdown_cnt',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='icxthumbup_cnt',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='thumbdown_cnt',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='thumbup_cnt',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thumbmodel',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SingleBoard',
        ),
    ]
